# Copyright (C) 2026 Innovyou
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import models


class FSMOrder(models.Model):
    _inherit = "fsm.order"

    def _sale_line_timesheet_material_orders(self):
        """Orders sold through a sale order line instead of a sale order.

        The orders generated by a recurring order are linked to the sale order
        line that sold the recurring order (see Field Service - Sales -
        Recurring), and have no sale order of their own. The work recorded on
        them still belongs to that sale order.
        """
        return self.filtered(lambda order: not order.sale_id and order.sale_line_id)

    def _prepare_sale_line_vals(self, product, qty, uom):
        vals = super()._prepare_sale_line_vals(product, qty, uom)
        if not self.sale_id:
            vals["order_id"] = self.sale_line_id.order_id.id
        return vals

    def action_create_sale_lines(self):
        for order in self._sale_line_timesheet_material_orders():
            order._create_sale_lines_from_timesheets()
            order._create_sale_lines_from_materials()
        return super().action_create_sale_lines()
