[project]
name = "odoo-addons-oca-field-service"
version = "19.0.20260623.3"
dependencies = [
    "odoo-addon-base_territory==19.0.*",
    "odoo-addon-fieldservice==19.0.*",
    "odoo-addon-fieldservice_calendar==19.0.*",
    "odoo-addon-fieldservice_equipment_stock==19.0.*",
    "odoo-addon-fieldservice_kanban_info==19.0.*",
    "odoo-addon-fieldservice_portal==19.0.*",
    "odoo-addon-fieldservice_recurring==19.0.*",
    "odoo-addon-fieldservice_stock==19.0.*",
    "odoo-addon-fieldservice_timesheet==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
