[project]
name = "odoo-addons-oca-field-service"
version = "18.0.20241022.0"
dependencies = [
    "odoo-addon-base_territory==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
