[project]
name = "odoo-addons-oca-field-service"
version = "19.0.20260722.0"
dependencies = [
    "odoo-addon-base_territory==19.0.*",
    "odoo-addon-fieldservice==19.0.*",
    "odoo-addon-fieldservice_account==19.0.*",
    "odoo-addon-fieldservice_activity==19.0.*",
    "odoo-addon-fieldservice_agreement==19.0.*",
    "odoo-addon-fieldservice_calendar==19.0.*",
    "odoo-addon-fieldservice_equipment_stock==19.0.*",
    "odoo-addon-fieldservice_equipment_warranty==19.0.*",
    "odoo-addon-fieldservice_expense==19.0.*",
    "odoo-addon-fieldservice_kanban_info==19.0.*",
    "odoo-addon-fieldservice_portal==19.0.*",
    "odoo-addon-fieldservice_project==19.0.*",
    "odoo-addon-fieldservice_purchase==19.0.*",
    "odoo-addon-fieldservice_recurring==19.0.*",
    "odoo-addon-fieldservice_sale==19.0.*",
    "odoo-addon-fieldservice_sale_agreement==19.0.*",
    "odoo-addon-fieldservice_sale_recurring==19.0.*",
    "odoo-addon-fieldservice_skill==19.0.*",
    "odoo-addon-fieldservice_stage_server_action==19.0.*",
    "odoo-addon-fieldservice_stock==19.0.*",
    "odoo-addon-fieldservice_timesheet==19.0.*",
    "odoo-addon-fieldservice_vehicle==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
