# Copyright 2026 Antoni Marroig (APSL-Nagarro) <antoni.marroig@nagarro.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import models


class StockMove(models.Model):
    _inherit = "stock.move"

    def _is_load_sheet_delivery(self):
        """Whether the move takes goods to the customer, so they have to be
        loaded. Pick-ups (from the customer, e.g. generated by negative sale
        order lines) are not, whatever the operation type of their transfer.

        Keep in sync with ``fsm.route.dayroute.product.summary._table_query``.
        """
        self.ensure_one()
        return (
            self.location_dest_id.usage == "customer"
            and self.location_id.usage != "customer"
        )

    def _is_load_sheet_pickup(self):
        """Whether the move brings goods back from the customer (e.g. generated
        by negative sale order lines): displayed per stop, but never loaded."""
        self.ensure_one()
        return (
            self.location_id.usage == "customer"
            and self.location_dest_id.usage != "customer"
        )
